# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: optiConfig.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='optiConfig.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10optiConfig.proto\"\xea\x05\n\x0fLayerOptiConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12-\n\tinputOpti\x18\x02 \x03(\x0b\x32\x1a.LayerOptiConfig.InputOpti\x12/\n\nweightOpti\x18\x03 \x03(\x0b\x32\x1b.LayerOptiConfig.WeightOpti\x12;\n\x10\x64oubleWeightOpti\x18\x04 \x03(\x0b\x32!.LayerOptiConfig.DoubleWeightOpti\x12;\n\x10sparseMatrixOpti\x18\x05 \x03(\x0b\x32!.LayerOptiConfig.SparseMatrixOpti\x12\x39\n\x0f\x61rrayOutputOpti\x18\x06 \x03(\x0b\x32 .LayerOptiConfig.ArrayOutputOpti\x12+\n\x08\x63onvOpti\x18\x07 \x03(\x0b\x32\x19.LayerOptiConfig.ConvOpti\x1aR\n\tInputOpti\x12\r\n\x05shift\x18\x01 \x01(\x05\x12\x0b\n\x03num\x18\x02 \x01(\x05\x12\x13\n\x0b\x66ront_scale\x18\x03 \x01(\x05\x12\x14\n\x0csigned_input\x18\x04 \x01(\x05\x1a\x46\n\nWeightOpti\x12\r\n\x05shift\x18\x01 \x01(\x05\x12\x0b\n\x03num\x18\x02 \x01(\x05\x12\x1c\n\x06region\x18\x03 \x01(\x0e\x32\x0c.ArrayRegion\x1a$\n\x10\x44oubleWeightOpti\x12\x10\n\x08multiple\x18\x01 \x01(\x05\x1a>\n\x10SparseMatrixOpti\x12\x1b\n\x07sp_mode\x18\x01 \x01(\x0e\x32\n.SpMatMode\x12\r\n\x05shift\x18\x02 \x01(\x05\x1a\x32\n\x0f\x41rrayOutputOpti\x12\x0f\n\x07magnify\x18\x01 \x01(\x05\x12\x0e\n\x06repeat\x18\x02 \x01(\x05\x1aQ\n\x08\x43onvOpti\x12\x13\n\x0bmulti_point\x18\x01 \x01(\x05\x12\x11\n\ttdnn_mode\x18\x02 \x01(\x08\x12\x1d\n\x15\x63onv2DToConv1D_enable\x18\x03 \x01(\x08\";\n\x0eOptimizeConfig\x12)\n\x0flayerOptiConfig\x18\x01 \x03(\x0b\x32\x10.LayerOptiConfig*5\n\tSpMatMode\x12\x0c\n\x08SIM_MODE\x10\x00\x12\x0c\n\x08MIX_MODE\x10\x01\x12\x0c\n\x08\x44IG_MODE\x10\x02*=\n\x0b\x41rrayRegion\x12\x0e\n\nANY_REGION\x10\x00\x12\r\n\tUP_REGION\x10\x01\x12\x0f\n\x0b\x44OWN_REGION\x10\x02\x62\x06proto3')
)

_SPMATMODE = _descriptor.EnumDescriptor(
  name='SpMatMode',
  full_name='SpMatMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SIM_MODE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIX_MODE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIG_MODE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=830,
  serialized_end=883,
)
_sym_db.RegisterEnumDescriptor(_SPMATMODE)

SpMatMode = enum_type_wrapper.EnumTypeWrapper(_SPMATMODE)
_ARRAYREGION = _descriptor.EnumDescriptor(
  name='ArrayRegion',
  full_name='ArrayRegion',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ANY_REGION', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UP_REGION', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOWN_REGION', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=885,
  serialized_end=946,
)
_sym_db.RegisterEnumDescriptor(_ARRAYREGION)

ArrayRegion = enum_type_wrapper.EnumTypeWrapper(_ARRAYREGION)
SIM_MODE = 0
MIX_MODE = 1
DIG_MODE = 2
ANY_REGION = 0
UP_REGION = 1
DOWN_REGION = 2



_LAYEROPTICONFIG_INPUTOPTI = _descriptor.Descriptor(
  name='InputOpti',
  full_name='LayerOptiConfig.InputOpti',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shift', full_name='LayerOptiConfig.InputOpti.shift', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num', full_name='LayerOptiConfig.InputOpti.num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='front_scale', full_name='LayerOptiConfig.InputOpti.front_scale', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signed_input', full_name='LayerOptiConfig.InputOpti.signed_input', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=458,
)

_LAYEROPTICONFIG_WEIGHTOPTI = _descriptor.Descriptor(
  name='WeightOpti',
  full_name='LayerOptiConfig.WeightOpti',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shift', full_name='LayerOptiConfig.WeightOpti.shift', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num', full_name='LayerOptiConfig.WeightOpti.num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='region', full_name='LayerOptiConfig.WeightOpti.region', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=460,
  serialized_end=530,
)

_LAYEROPTICONFIG_DOUBLEWEIGHTOPTI = _descriptor.Descriptor(
  name='DoubleWeightOpti',
  full_name='LayerOptiConfig.DoubleWeightOpti',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='multiple', full_name='LayerOptiConfig.DoubleWeightOpti.multiple', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=568,
)

_LAYEROPTICONFIG_SPARSEMATRIXOPTI = _descriptor.Descriptor(
  name='SparseMatrixOpti',
  full_name='LayerOptiConfig.SparseMatrixOpti',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sp_mode', full_name='LayerOptiConfig.SparseMatrixOpti.sp_mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shift', full_name='LayerOptiConfig.SparseMatrixOpti.shift', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=570,
  serialized_end=632,
)

_LAYEROPTICONFIG_ARRAYOUTPUTOPTI = _descriptor.Descriptor(
  name='ArrayOutputOpti',
  full_name='LayerOptiConfig.ArrayOutputOpti',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='magnify', full_name='LayerOptiConfig.ArrayOutputOpti.magnify', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repeat', full_name='LayerOptiConfig.ArrayOutputOpti.repeat', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=634,
  serialized_end=684,
)

_LAYEROPTICONFIG_CONVOPTI = _descriptor.Descriptor(
  name='ConvOpti',
  full_name='LayerOptiConfig.ConvOpti',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='multi_point', full_name='LayerOptiConfig.ConvOpti.multi_point', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tdnn_mode', full_name='LayerOptiConfig.ConvOpti.tdnn_mode', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conv2DToConv1D_enable', full_name='LayerOptiConfig.ConvOpti.conv2DToConv1D_enable', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=686,
  serialized_end=767,
)

_LAYEROPTICONFIG = _descriptor.Descriptor(
  name='LayerOptiConfig',
  full_name='LayerOptiConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='LayerOptiConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputOpti', full_name='LayerOptiConfig.inputOpti', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weightOpti', full_name='LayerOptiConfig.weightOpti', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='doubleWeightOpti', full_name='LayerOptiConfig.doubleWeightOpti', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sparseMatrixOpti', full_name='LayerOptiConfig.sparseMatrixOpti', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arrayOutputOpti', full_name='LayerOptiConfig.arrayOutputOpti', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='convOpti', full_name='LayerOptiConfig.convOpti', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LAYEROPTICONFIG_INPUTOPTI, _LAYEROPTICONFIG_WEIGHTOPTI, _LAYEROPTICONFIG_DOUBLEWEIGHTOPTI, _LAYEROPTICONFIG_SPARSEMATRIXOPTI, _LAYEROPTICONFIG_ARRAYOUTPUTOPTI, _LAYEROPTICONFIG_CONVOPTI, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=767,
)


_OPTIMIZECONFIG = _descriptor.Descriptor(
  name='OptimizeConfig',
  full_name='OptimizeConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layerOptiConfig', full_name='OptimizeConfig.layerOptiConfig', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=769,
  serialized_end=828,
)

_LAYEROPTICONFIG_INPUTOPTI.containing_type = _LAYEROPTICONFIG
_LAYEROPTICONFIG_WEIGHTOPTI.fields_by_name['region'].enum_type = _ARRAYREGION
_LAYEROPTICONFIG_WEIGHTOPTI.containing_type = _LAYEROPTICONFIG
_LAYEROPTICONFIG_DOUBLEWEIGHTOPTI.containing_type = _LAYEROPTICONFIG
_LAYEROPTICONFIG_SPARSEMATRIXOPTI.fields_by_name['sp_mode'].enum_type = _SPMATMODE
_LAYEROPTICONFIG_SPARSEMATRIXOPTI.containing_type = _LAYEROPTICONFIG
_LAYEROPTICONFIG_ARRAYOUTPUTOPTI.containing_type = _LAYEROPTICONFIG
_LAYEROPTICONFIG_CONVOPTI.containing_type = _LAYEROPTICONFIG
_LAYEROPTICONFIG.fields_by_name['inputOpti'].message_type = _LAYEROPTICONFIG_INPUTOPTI
_LAYEROPTICONFIG.fields_by_name['weightOpti'].message_type = _LAYEROPTICONFIG_WEIGHTOPTI
_LAYEROPTICONFIG.fields_by_name['doubleWeightOpti'].message_type = _LAYEROPTICONFIG_DOUBLEWEIGHTOPTI
_LAYEROPTICONFIG.fields_by_name['sparseMatrixOpti'].message_type = _LAYEROPTICONFIG_SPARSEMATRIXOPTI
_LAYEROPTICONFIG.fields_by_name['arrayOutputOpti'].message_type = _LAYEROPTICONFIG_ARRAYOUTPUTOPTI
_LAYEROPTICONFIG.fields_by_name['convOpti'].message_type = _LAYEROPTICONFIG_CONVOPTI
_OPTIMIZECONFIG.fields_by_name['layerOptiConfig'].message_type = _LAYEROPTICONFIG
DESCRIPTOR.message_types_by_name['LayerOptiConfig'] = _LAYEROPTICONFIG
DESCRIPTOR.message_types_by_name['OptimizeConfig'] = _OPTIMIZECONFIG
DESCRIPTOR.enum_types_by_name['SpMatMode'] = _SPMATMODE
DESCRIPTOR.enum_types_by_name['ArrayRegion'] = _ARRAYREGION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LayerOptiConfig = _reflection.GeneratedProtocolMessageType('LayerOptiConfig', (_message.Message,), dict(

  InputOpti = _reflection.GeneratedProtocolMessageType('InputOpti', (_message.Message,), dict(
    DESCRIPTOR = _LAYEROPTICONFIG_INPUTOPTI,
    __module__ = 'optiConfig_pb2'
    # @@protoc_insertion_point(class_scope:LayerOptiConfig.InputOpti)
    ))
  ,

  WeightOpti = _reflection.GeneratedProtocolMessageType('WeightOpti', (_message.Message,), dict(
    DESCRIPTOR = _LAYEROPTICONFIG_WEIGHTOPTI,
    __module__ = 'optiConfig_pb2'
    # @@protoc_insertion_point(class_scope:LayerOptiConfig.WeightOpti)
    ))
  ,

  DoubleWeightOpti = _reflection.GeneratedProtocolMessageType('DoubleWeightOpti', (_message.Message,), dict(
    DESCRIPTOR = _LAYEROPTICONFIG_DOUBLEWEIGHTOPTI,
    __module__ = 'optiConfig_pb2'
    # @@protoc_insertion_point(class_scope:LayerOptiConfig.DoubleWeightOpti)
    ))
  ,

  SparseMatrixOpti = _reflection.GeneratedProtocolMessageType('SparseMatrixOpti', (_message.Message,), dict(
    DESCRIPTOR = _LAYEROPTICONFIG_SPARSEMATRIXOPTI,
    __module__ = 'optiConfig_pb2'
    # @@protoc_insertion_point(class_scope:LayerOptiConfig.SparseMatrixOpti)
    ))
  ,

  ArrayOutputOpti = _reflection.GeneratedProtocolMessageType('ArrayOutputOpti', (_message.Message,), dict(
    DESCRIPTOR = _LAYEROPTICONFIG_ARRAYOUTPUTOPTI,
    __module__ = 'optiConfig_pb2'
    # @@protoc_insertion_point(class_scope:LayerOptiConfig.ArrayOutputOpti)
    ))
  ,

  ConvOpti = _reflection.GeneratedProtocolMessageType('ConvOpti', (_message.Message,), dict(
    DESCRIPTOR = _LAYEROPTICONFIG_CONVOPTI,
    __module__ = 'optiConfig_pb2'
    # @@protoc_insertion_point(class_scope:LayerOptiConfig.ConvOpti)
    ))
  ,
  DESCRIPTOR = _LAYEROPTICONFIG,
  __module__ = 'optiConfig_pb2'
  # @@protoc_insertion_point(class_scope:LayerOptiConfig)
  ))
_sym_db.RegisterMessage(LayerOptiConfig)
_sym_db.RegisterMessage(LayerOptiConfig.InputOpti)
_sym_db.RegisterMessage(LayerOptiConfig.WeightOpti)
_sym_db.RegisterMessage(LayerOptiConfig.DoubleWeightOpti)
_sym_db.RegisterMessage(LayerOptiConfig.SparseMatrixOpti)
_sym_db.RegisterMessage(LayerOptiConfig.ArrayOutputOpti)
_sym_db.RegisterMessage(LayerOptiConfig.ConvOpti)

OptimizeConfig = _reflection.GeneratedProtocolMessageType('OptimizeConfig', (_message.Message,), dict(
  DESCRIPTOR = _OPTIMIZECONFIG,
  __module__ = 'optiConfig_pb2'
  # @@protoc_insertion_point(class_scope:OptimizeConfig)
  ))
_sym_db.RegisterMessage(OptimizeConfig)


# @@protoc_insertion_point(module_scope)
